# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rater',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Rater'),
        ),
    ]
