# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 19:26
from __future__ import unicode_literals

from django.db import migrations
from movie.worker import import_all_data


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(import_all_data)
    ]
