# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20160607_1847'),
    ]

    operations = [
    ]
